management.endpoints.web.exposure.include: "*"

server:
  port: 8081
spring:
  application:
    name: "spring-web-request"
  boot:
    admin:
      client:
        url: "http://localhost:8080"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true


info:
  app:
    version: 1.0.0
logging:
  file: app.log
